### ISSUE TITLE
Package Error

### ISSUE THREAD

**Issue by Tim4DConstruct** [iTwin/itwin-unreal-plugin#73]
Yesterday I updated to the latest plugin version. And I have been getting errors.

There seems to be some kind of access denied.

UATHelper: Packaging (Windows): Setting up ProjectParams for C:\Users\TimvanNuland\Documents\Unreal Projects\Nijmegen_PC\Nijmegen_PC.uproject
UATHelper: Packaging (Windows): ********** BUILD COMMAND STARTED **********
UATHelper: Packaging (Windows): Running: C:\Program Files\Epic Games\UE_5.3\Engine\Binaries\ThirdParty\DotNet\6.0.302\windows\dotnet.exe "C:\Program Files\Epic Games\UE_5.3\Engine\Binaries\DotNET\UnrealBuildTool\UnrealBuildTool.dll" iTwinTemplate Win64 Shipping -Project="C:\Users\TimvanNuland\Documents\Unreal Projects\Nijmegen_PC\Nijmegen_PC.uproject" -Manifest="C:\Users\TimvanNuland\Documents\Unreal Projects\Nijmegen_PC\Intermediate\Build\Manifest.xml"  -remoteini="C:\Users\TimvanNuland\Documents\Unreal Projects\Nijmegen_PC"  -skipdeploy  -log="C:\Users\TimvanNuland\AppData\Roaming\Unreal Eng
ine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.3\UBT-iTwinTemplate-Win64-Shipping.txt"
UATHelper: Packaging (Windows): Log file: C:\Users\TimvanNuland\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.3\UBT-iTwinTemplate-Win64-Shipping.txt
UATHelper: Packaging (Windows): Creating makefile for iTwinTemplate (manifest 'C:\Users\TimvanNuland\Documents\Unreal Projects\Nijmegen_PC\Intermediate\Build\Manifest.xml' not found)
UATHelper: Packaging (Windows): bBeUseUnity ITwinRuntime = True
UATHelper: Packaging (Windows): Writing manifest to C:\Users\TimvanNuland\Documents\Unreal Projects\Nijmegen_PC\Intermediate\Build\Manifest.xml
UATHelper: Packaging (Windows): Failed to delete file 'C:\Users\TimvanNuland\Documents\Unreal Projects\Nijmegen_PC\Binaries\Win64\Singleton.dll'
UATHelper: Packaging (Windows):     Exception: Access to the path 'C:\Users\TimvanNuland\Documents\Unreal Projects\Nijmegen_PC\Binaries\Win64\Singleton.dll' is denied.
UATHelper: Packaging (Windows): Attempting to retry...
UATHelper: Packaging (Windows): Failed to delete file 'C:\Users\TimvanNuland\Documents\Unreal Projects\Nijmegen_PC\Binaries\Win64\Singleton.dll'
UATHelper: Packaging (Windows):     Exception: Access to the path 'C:\Users\TimvanNuland\Documents\Unreal Projects\Nijmegen_PC\Binaries\Win64\Singleton.dll' is denied.
UATHelper: Packaging (Windows): Attempting to retry...
UATHelper: Packaging (Windows): Failed to delete file 'C:\Users\TimvanNuland\Documents\Unreal Projects\Nijmegen_PC\Binaries\Win64\Singleton.dll'
UATHelper: Packaging (Windows):     Exception: Access to the path 'C:\Users\TimvanNuland\Documents\Unreal Projects\Nijmegen_PC\Binaries\Win64\Singleton.dll' is denied.
UATHelper: Packaging (Windows): ERROR: Exhausted all retries!
UATHelper: Packaging (Windows): Building iTwinTemplate...
UATHelper: Packaging (Windows): Using Visual Studio 2022 14.43.34808 toolchain (C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.43.34808) and Windows 10.0.22621.0 SDK (C:\Program Files (x86)\Windows Kits\10).
PackagingResults: Error: Exhausted all retries!
UATHelper: Packaging (Windows): Determining max actions to execute in parallel (24 physical cores, 32 logical cores)
UATHelper: Packaging (Windows):   Executing up to 24 processes, one per physical core
UATHelper: Packaging (Windows): ------ Building 3 action(s) started ------
UATHelper: Packaging (Windows): [1/3] Copy Singleton.dll
UATHelper: Packaging (Windows): The process cannot access the file because it is being used by another process.
UATHelper: Packaging (Windows): [2/3] Link [x64] iTwinTemplate-Win64-Shipping.exe
UATHelper: Packaging (Windows):    Creating library C:\Users\TimvanNuland\Documents\Unreal Projects\Nijmegen_PC\Binaries\Win64\iTwinTemplate-Win64-Shipping.lib and object C:\Users\TimvanNuland\Documents\Unreal Projects\Nijmegen_PC\Binaries\Win64\iTwinTemplate-Win64-Shipping.exp
UATHelper: Packaging (Windows): Visualization.lib(MaterialPersistence.obj) : error LNK2019: unresolved external symbol __std_find_first_of_trivial_pos_1 referenced in function "unsigned __int64 __cdecl std::_Find_first_of_pos_vectorized<char,char>(char const * const,unsigned __int64,char const * const,unsigned __int64)" (??$_Find_first_of_pos_vectorized@DD@std@@YA_KQEBD_K01@Z)
UATHelper: Packaging (Windows): Visualization.lib(ITwinWebServices.obj) : error LNK2001: unresolved external symbol __std_find_first_of_trivial_pos_1
UATHelper: Packaging (Windows): assert.lib(utils.cpp.obj) : error LNK2001: unresolved external symbol __std_find_first_of_trivial_pos_1
UATHelper: Packaging (Windows): cpr.lib(util.cpp.obj) : error LNK2001: unresolved external symbol __std_find_first_of_trivial_pos_1
UATHelper: Packaging (Windows): C:\Users\TimvanNuland\Documents\Unreal Projects\Nijmegen_PC\Binaries\Win64\iTwinTemplate-Win64-Shipping.exe : fatal error LNK1120: 1 unresolved externals
UATHelper: Packaging (Windows): Total time in Parallel executor: 7.45 seconds
UATHelper: Packaging (Windows): Total execution time: 10.82 seconds
UATHelper: Packaging (Windows): Took 10,92s to run dotnet.exe, ExitCode=6
UATHelper: Packaging (Windows): UnrealBuildTool failed. See log for more details. (C:\Users\TimvanNuland\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.3\UBT-iTwinTemplate-Win64-Shipping.txt)
UATHelper: Packaging (Windows): AutomationTool executed for 0h 0m 12s
UATHelper: Packaging (Windows): AutomationTool exiting with ExitCode=6 (6)
UATHelper: Packaging (Windows): BUILD FAILED
PackagingResults: Error: Unknown Error

**Comment by GhisBntly** [comment]
Alas, I do not reproduce either in my test project even with the 17.11 toolchain (14.41.34123, very close to what I see above, probably just a couple patch versions away) :-(
I will try a more substantial test project.

I think developers over here had similar issues when mixing different toolchain versions between vcpkg and Unreal, but I guess you are reusing the precompiled binaries, not rebuilding the whole plugin (as explained here https://github.com/iTwin/itwin-unreal-plugin/tree/main/Documentation/ForDevelopers#build-and-run-on-windows), right?

I also see `Windows 10.0.22621.0` in the logs: the plugin was built on Windows 10 too at the time, but maybe the SDK version can have an effect. I'll see if I can try with an older SDK as well.

**Comment by Tim4DConstruct** [comment]
Found these 3. Do I have to do that with all of these or just one? And for each project?

LogMonitoredProcess: Running Serialized UAT: [ cmd.exe /c ""C:/Program Files/Epic Games/UE_5.3/Engine/Build/BatchFiles/RunUAT.bat"  -ScriptsForProject="C:/Users/TimvanNuland/Documents/Unreal Projects/Template_PC/Template_PC.uproject" Turnkey -utf8output -WaitForUATMutex -command=VerifySdk -ReportFilename="C:/Users/TimvanNuland/Documents/Unreal Projects/Template_PC/Intermediate/TurnkeyReport_0.log" -log="C:/Users/TimvanNuland/Documents/Unreal Projects/Template_PC/Intermediate/TurnkeyLog_0.log" -project="C:/Users/TimvanNuland/Documents/Unreal Projects/Template_PC/Template_PC.uproject"  -platform
LogMonitoredProcess: Running Serialized UAT: [ cmd.exe /c ""C:/Program Files/Epic Games/UE_5.3/Engine/Build/BatchFiles/RunUAT.bat"  -ScriptsForProject="C:/Users/TimvanNuland/Documents/Unreal Projects/Template_PC/Template_PC.uproject" Turnkey -utf8output -WaitForUATMutex -command=VerifySdk -ReportFilename="C:/Users/TimvanNuland/Documents/Unreal Projects/Template_PC/Intermediate/TurnkeyReport_1.log" -log="C:/Users/TimvanNuland/Documents/Unreal Projects/Template_PC/Intermediate/TurnkeyLog_1.log" -project="C:/Users/TimvanNuland/Documents/Unreal Projects/Template_PC/Template_PC.uproject"  -Device=W
LogMonitoredProcess: Running Serialized UAT: [ cmd.exe /c ""C:/Program Files/Epic Games/UE_5.3/Engine/Build/BatchFiles/RunUAT.bat"  -ScriptsForProject="C:/Users/TimvanNuland/Documents/Unreal Projects/Template_PC/Template_PC.uproject" Turnkey -command=VerifySdk -platform=Win64 -UpdateIfNeeded -EditorIO -EditorIOPort=55255  -project="C:/Users/TimvanNuland/Documents/Unreal Projects/Template_PC/Template_PC.uproject" BuildCookRun -nop4 -utf8output -nocompileeditor -skipbuildeditor -cook  -project="C:/Users/TimvanNuland/Documents/Unreal Projects/Template_PC/Template_PC.uproject" -target=iTwinTemplat

**Comment by Tim4DConstruct** [comment]
Getting link errors now:

UATHelper: Packaging (Windows): ********** BUILD COMMAND STARTED **********
UATHelper: Packaging (Windows): Running: C:\Program Files\Epic Games\UE_5.3\Engine\Binaries\ThirdParty\DotNet\6.0.302\windows\dotnet.exe "C:\Program Files\Epic Games\UE_5.3\Engine\Binaries\DotNET\UnrealBuildTool\UnrealBuildTool.dll" iTwinTemplate Win64 Shipping -Project="C:\Users\TimvanNuland\Documents\Unreal Projects\PC_Template\PC_Template.uproject" -Manifest="C:\Users\TimvanNuland\Documents\Unreal Projects\PC_Template\Intermediate\Build\Manifest.xml"  -remoteini="C:\Users\TimvanNuland\Documents\Unreal Projects\PC_Template"  -skipdeploy  -log="C:\Users\TimvanNuland\AppData\Roaming\Unreal Eng
ine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.3\UBT-iTwinTemplate-Win64-Shipping.txt"
UATHelper: Packaging (Windows): Log file: C:\Users\TimvanNuland\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.3\UBT-iTwinTemplate-Win64-Shipping.txt
UATHelper: Packaging (Windows): Creating makefile for iTwinTemplate (manifest 'C:\Users\TimvanNuland\Documents\Unreal Projects\PC_Template\Intermediate\Build\Manifest.xml' not found)
UATHelper: Packaging (Windows): bBeUseUnity ITwinRuntime = True
UATHelper: Packaging (Windows): Writing manifest to C:\Users\TimvanNuland\Documents\Unreal Projects\PC_Template\Intermediate\Build\Manifest.xml
UATHelper: Packaging (Windows): Building iTwinTemplate...
UATHelper: Packaging (Windows): Using Visual Studio 2022 14.43.34808 toolchain (C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.43.34808) and Windows 10.0.22621.0 SDK (C:\Program Files (x86)\Windows Kits\10).
UATHelper: Packaging (Windows): Determining max actions to execute in parallel (24 physical cores, 32 logical cores)
UATHelper: Packaging (Windows):   Executing up to 24 processes, one per physical core
UATHelper: Packaging (Windows): ------ Building 2 action(s) started ------
UATHelper: Packaging (Windows): [1/2] Link [x64] iTwinTemplate-Win64-Shipping.exe
UATHelper: Packaging (Windows):    Creating library C:\Users\TimvanNuland\Documents\Unreal Projects\PC_Template\Binaries\Win64\iTwinTemplate-Win64-Shipping.lib and object C:\Users\TimvanNuland\Documents\Unreal Projects\PC_Template\Binaries\Win64\iTwinTemplate-Win64-Shipping.exp
UATHelper: Packaging (Windows): Visualization.lib(MaterialPersistence.obj) : error LNK2019: unresolved external symbol __std_find_first_of_trivial_pos_1 referenced in function "unsigned __int64 __cdecl std::_Find_first_of_pos_vectorized<char,char>(char const * const,unsigned __int64,char const * const,unsigned __int64)" (??$_Find_first_of_pos_vectorized@DD@std@@YA_KQEBD_K01@Z)
UATHelper: Packaging (Windows): Visualization.lib(ITwinWebServices.obj) : error LNK2001: unresolved external symbol __std_find_first_of_trivial_pos_1
UATHelper: Packaging (Windows): assert.lib(utils.cpp.obj) : error LNK2001: unresolved external symbol __std_find_first_of_trivial_pos_1
UATHelper: Packaging (Windows): cpr.lib(util.cpp.obj) : error LNK2001: unresolved external symbol __std_find_first_of_trivial_pos_1
UATHelper: Packaging (Windows): C:\Users\TimvanNuland\Documents\Unreal Projects\PC_Template\Binaries\Win64\iTwinTemplate-Win64-Shipping.exe : fatal error LNK1120: 1 unresolved externals
UATHelper: Packaging (Windows): Total time in Parallel executor: 6.56 seconds
UATHelper: Packaging (Windows): Total execution time: 7.86 seconds
UATHelper: Packaging (Windows): Took 7,98s to run dotnet.exe, ExitCode=6
UATHelper: Packaging (Windows): UnrealBuildTool failed. See log for more details. (C:\Users\TimvanNuland\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.3\UBT-iTwinTemplate-Win64-Shipping.txt)
UATHelper: Packaging (Windows): AutomationTool executed for 0h 0m 9s
UATHelper: Packaging (Windows): AutomationTool exiting with ExitCode=6 (6)
UATHelper: Packaging (Windows): BUILD FAILED
PackagingResults: Error: Unknown Error

**Comment by Tim4DConstruct** [comment]
It has worked, i can package again after I updated to 17.14.18.
